# Site settings
title: Benjiminius
email: ben.alderfer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/my-blog/" # the subpath of your site, e.g. /blog/
url: "http://benalderfer.com" # the base hostname & protocol for your site
twitter_username: ben_ald
github_username:  balderfer

# Build settings
markdown: kramdown
